---
# tasks file for loadbalancer

- name: Installing HAProxy
  package:
    name: "haproxy" 
    state: present
  become: true

- name: Copying configuration
  template:
    src: "/etc/haproxy/haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Restart
  become: true

- name: Starting HAProxy services
  service: 
    name: "haproxy"
    state: started
  become: true
